apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
spec:
  selector:
    matchLabels:
      app: weaviate
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate-server
          image: cr.weaviate.io/semitechnologies/weaviate:1.19.6
          ports:
            - containerPort: 8080
              name: api-port
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: '/data/weaviate'
            - name: DEFAULT_VECTORIZER_MODULE
              value: 'none'
            - name: CLUSTER_HOSTNAME
              value: 'weaviate1'
          volumeMounts:
            - mountPath: /data
              name: temp-volume
      volumes:
        - name: temp-volume
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate-service
spec:
  selector:
    app: weaviate
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: api-port
